name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    name: Test
    runs-on: ubuntu-latest
    env: 
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=localhost port=5432 dbname=simple_bank user=root password=password connect_timeout=10 sslmode=disable

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: install goose
      run: go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: run migrations
      run: make gooseup

    - name: Test
      run: make test
